import uuid
from django.db import models


class Resource(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    standard = models.PositiveIntegerField()
    subject = models.CharField(max_length=100)

    file_name = models.CharField(max_length=255)
    file_hash = models.CharField(
        max_length=64,
        unique=True,
        help_text="SHA256 hash of file for idempotency"
    )

    source_path = models.CharField(
        max_length=500,
        help_text="Local or cloud path of uploaded file"
    )

    is_active = models.BooleanField(
        default=True,
        help_text="If re-uploaded, old resource can be marked inactive"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "resources"
        indexes = [
            models.Index(fields=["standard", "subject"]),
        ]

    def __str__(self):
        return f"{self.standard} {self.subject} - {self.file_name}"


class Chapter(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    resource = models.ForeignKey(
        Resource,
        on_delete=models.CASCADE,
        related_name="chapters"
    )

    chapter_name = models.CharField(max_length=255)
    chapter_number = models.PositiveIntegerField(null=True, blank=True)

    standard = models.PositiveIntegerField()
    subject = models.CharField(max_length=100)

    full_text = models.TextField(
        help_text="Complete chapter text extracted from PDF"
    )

    ai_summary = models.TextField(
        null=True,
        blank=True,
        help_text="Optional AI-generated chapter summary"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "chapters"
        unique_together = ("standard", "subject", "chapter_name")

    def __str__(self):
        return self.chapter_name


class Topic(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    chapter = models.ForeignKey(
        Chapter,
        on_delete=models.CASCADE,
        related_name="topics"
    )

    topic_name = models.CharField(max_length=255)

    topic_content = models.TextField(
        help_text="AI-generated explanation / main points"
    )

    # Optional simplified version generated by AI (stored as list of lines)
    simplified_content = models.JSONField(
        null=True,
        blank=True,
        help_text="AI-generated simplified content stored as a list of strings",
    )

    order = models.PositiveIntegerField(
        default=0,
        help_text="Display order in UI"
    )

    # simplified_version = models.TextField(
    #     null=True,
    #     blank=True,
    #     help_text="AI-generated simplified version with analogies"
    # )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "topics"
        unique_together = ("chapter", "topic_name")
        ordering = ["order"]

    def __str__(self):
        return self.topic_name

class Question(models.Model):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"

    LEVEL_CHOICES = [
        (EASY, "Easy"),
        (MEDIUM, "Medium"),
        (HARD, "Hard"),
    ]

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    chapter = models.ForeignKey(
        Chapter,
        on_delete=models.CASCADE,
        related_name="questions"
    )

    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="questions"
    )

    question_level = models.CharField(
        max_length=10,
        choices=LEVEL_CHOICES
    )

    question_text = models.TextField()

    question_type = models.CharField(
        max_length=20,
        default="MCQ",
        help_text="Type of question, e.g. MCQ, Theory"
    )

    options = models.JSONField(
        help_text="MCQ options as JSON"
        # Example:
        # { "A": "2", "B": "4", "C": "6", "D": "8" }
    )

    correct_answer = models.CharField(
        max_length=5,
        help_text="Correct option key, e.g. A/B/C/D"
    )

    explanation = models.TextField(
        null=True,
        blank=True,
        help_text="Optional AI explanation"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "questions"

    def __str__(self):
        return self.question_text[:80]
