# Generated by Django 6.0.1 on 2026-01-20 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PRINCIPAL', 'Principal'), ('DISTRICT_MANAGER', 'District Manager'), ('STATE_MANAGER', 'State Manager')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft disable role without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'unique_together': {('year_start', 'year_end')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'grades',
                'unique_together': {('number',)},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA256 hash of file for idempotency', max_length=64, unique=True)),
                ('source_path', models.CharField(help_text='Local or cloud path of uploaded file', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='If re-uploaded, old resource can be marked inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
                'indexes': [models.Index(fields=['standard', 'subject'], name='resources_standar_0b92a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('standard', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('full_text', models.TextField(help_text='Complete chapter text extracted from PDF')),
                ('ai_summary', models.TextField(blank=True, help_text='Optional AI-generated chapter summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='database.resource')),
            ],
            options={
                'db_table': 'chapters',
                'unique_together': {('standard', 'subject', 'chapter_name')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='database.district')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='ManagementScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.school')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.state')),
            ],
            options={
                'db_table': 'management_scopes',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='database.state'),
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_assignments',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('topic_content', models.TextField(help_text='AI-generated explanation / main points')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='database.chapter')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['order'],
                'unique_together': {('chapter', 'topic_name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='MCQ options as JSON')),
                ('correct_answer', models.CharField(help_text='Correct option key, e.g. A/B/C/D', max_length=5)),
                ('explanation', models.TextField(blank=True, help_text='Optional AI explanation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='database.chapter')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='database.topic')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PROMOTED', 'Promoted'), ('REPEAT', 'Repeat'), ('DROPPED', 'Dropped')], help_text='Set at end of academic year', max_length=20, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='database.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'indexes': [models.Index(fields=['user'], name='user_roles_user_id_05df60_idx'), models.Index(fields=['role'], name='user_roles_role_id_0b583b_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
