# Generated by Django 6.0.1 on 2026-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(default='OG', help_text='E.g. OG, Easy etc.', max_length=100),
        ),
    ]
