# Generated by Django 6.0.1 on 2026-01-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_topic_topic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='topic',
            name='simplified_version',
            field=models.TextField(blank=True, help_text='AI-generated simplified version with analogies', null=True),
        ),
    ]
