# Generated by Django 6.0.1 on 2026-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_topic_topic_type_topic_simplified_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='simplified_version',
        ),
        migrations.AddField(
            model_name='topic',
            name='simplified_content',
            field=models.JSONField(blank=True, help_text='AI-generated simplified content stored as a list of strings', null=True),
        ),
    ]
