# Generated by Django 6.0.1 on 2026-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_topic_simplified_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='MCQ', help_text='Type of question, e.g. MCQ, Theory', max_length=20),
        ),
    ]
